baseURL = "http://localhost"
languageCode = "en-us"
title = "Wardrobe"
theme = "tinyworks"

[params]
    mainbg = "/img/END OF SEASON SALE (1).png"
    name = "Sumi"
    maintitle = "Sumi's Love"
    



