baseURL = "http://localhost"
languageCode = "en-us"
title = "Sumi's Love"
theme = "tinyworks"

[params]
    mainbg = "img/main.jpg"
    name = "Sumi"
    mainTitle = ""
    mainText = "Welcome to  my crafting blog"



